options:
  formatter: stylish
files:
  include: 'src/**/*.scss'
rules:
  indentation:
    - 1
    - size: tab
  nesting-depth:
    - 1
    - max-depth: 4
  no-duplicate-properties: 1
  no-ids: 0
  no-important: 0
  final-newline: 0